/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author LUCYLEONOR
 */
public class VectorTres extends javax.swing.JFrame {

    /**
     * Creates new form VectorTres
     */
    
    double v1[];
    double v2[];
    double vS[];
    double vR[];
    double v3[];
    public VectorTres() {
        initComponents();
        cmdLlenadoM1.setEnabled(false);
        cmdLlenadoA1.setEnabled(false);
        cmdMostrar1.setEnabled(false);
        cmdLlenadoM2.setEnabled(false);
        cmdLlenadoA2.setEnabled(false);
        cmdMostrar2.setEnabled(false);
        cmdCalcular.setEnabled(true);
        cmdBorrarTodo.setEnabled(true);
        txtLU.requestFocusInWindow();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtLD = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cmdCrear2 = new javax.swing.JButton();
        cmdLlenadoM2 = new javax.swing.JButton();
        cmdLlenadoA2 = new javax.swing.JButton();
        cmdBorrar2 = new javax.swing.JButton();
        cmdMostrar2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtR = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEU = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtLU = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtED = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        cmdCrear1 = new javax.swing.JButton();
        cmdLlenadoM1 = new javax.swing.JButton();
        cmdLlenadoA1 = new javax.swing.JButton();
        cmdBorrar1 = new javax.swing.JButton();
        cmdMostrar1 = new javax.swing.JButton();
        cmdCalcular = new javax.swing.JButton();
        cmdBorrarTodo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vector Suma Y Resta");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Vector Multifuncional");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vector Dos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Longitud");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtLD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLDKeyTyped(evt);
            }
        });
        jPanel4.add(txtLD, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 90, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 250, 70));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCrear2.setText("Crear");
        cmdCrear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrear2ActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCrear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, -1));

        cmdLlenadoM2.setText("Llenado Manual");
        cmdLlenadoM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenadoM2ActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLlenadoM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 150, -1));

        cmdLlenadoA2.setText("Llenado Automatico");
        cmdLlenadoA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenadoA2ActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLlenadoA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, -1));

        cmdBorrar2.setText("Borrar Vector Dos");
        cmdBorrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrar2ActionPerformed(evt);
            }
        });
        jPanel3.add(cmdBorrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 150, -1));

        cmdMostrar2.setText("Mostrar Vector Dos");
        cmdMostrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrar2ActionPerformed(evt);
            }
        });
        jPanel3.add(cmdMostrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 170, 310));

        txtR.setEditable(false);
        txtR.setColumns(20);
        txtR.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtR.setRows(5);
        txtR.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jScrollPane1.setViewportView(txtR);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 290, 120));

        txtEU.setEditable(false);
        txtEU.setColumns(20);
        txtEU.setRows(5);
        txtEU.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Elementos Del Vector Uno", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jScrollPane2.setViewportView(txtEU);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 290, 120));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vector Uno", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Longitud");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtLU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLUKeyTyped(evt);
            }
        });
        jPanel5.add(txtLU, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 90, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 250, 70));

        txtED.setColumns(20);
        txtED.setRows(5);
        txtED.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Elementos Del Vector Dos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jScrollPane3.setViewportView(txtED);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 290, 120));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCrear1.setText("Crear");
        cmdCrear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrear1ActionPerformed(evt);
            }
        });
        jPanel6.add(cmdCrear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, -1));

        cmdLlenadoM1.setText("Llenado Manual");
        cmdLlenadoM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenadoM1ActionPerformed(evt);
            }
        });
        jPanel6.add(cmdLlenadoM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 150, -1));

        cmdLlenadoA1.setText("Llenado Automatico");
        cmdLlenadoA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenadoA1ActionPerformed(evt);
            }
        });
        jPanel6.add(cmdLlenadoA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, -1));

        cmdBorrar1.setText("Borrar Vector Uno");
        cmdBorrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrar1ActionPerformed(evt);
            }
        });
        jPanel6.add(cmdBorrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 150, -1));

        cmdMostrar1.setText("Mostrar Vector Uno");
        cmdMostrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrar1ActionPerformed(evt);
            }
        });
        jPanel6.add(cmdMostrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, 30));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 170, 310));

        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel2.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 170, -1));

        cmdBorrarTodo.setText("Borrar Todo");
        cmdBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarTodoActionPerformed(evt);
            }
        });
        jPanel2.add(cmdBorrarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 170, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLDKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_txtLDKeyTyped

    private void cmdCrear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrear2ActionPerformed

        int L2;
        
        if (txtLD.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite La Longitud", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtLD.requestFocusInWindow();
        } else if (Integer.parseInt(txtLD.getText().trim()) == 0){
            JOptionPane.showMessageDialog(this, "Digite Una Longitud Superior A 0", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtLD.requestFocusInWindow();
            txtLD.selectAll();
        }
        else {
            
            
            
            L2 = Integer.parseInt(txtLD.getText());
            v2 = new double[L2];
            JOptionPane.showMessageDialog(this, "Vector Creado Satisfatoriamente");
            txtLD.setText("");
            
            
            cmdCrear2.setEnabled(false);
            cmdLlenadoM2.setEnabled(true);
            cmdLlenadoA2.setEnabled(true);
            cmdMostrar2.setEnabled(false);
            cmdBorrar2.setEnabled(true);
            txtLD.setEditable(false);
            
        }
    }//GEN-LAST:event_cmdCrear2ActionPerformed

    private void cmdLlenadoM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenadoM2ActionPerformed

        double n;
        
         for (int i = 0; i < v2.length; i++) {

            n = Double.parseDouble(JOptionPane.showInputDialog("Digite el elemento de la posicion " + i + " Del Vector Uno"));
            v2[i] = n;

                  }
        
        
        JOptionPane.showMessageDialog(this, "Vector Llenado Con Exito");

        cmdCrear2.setEnabled(false);
        cmdLlenadoM2.setEnabled(false);
        cmdLlenadoA2.setEnabled(false);
        cmdMostrar2.setEnabled(true);
        cmdBorrar2.setEnabled(true);
        txtLD.setEditable(false);
    }//GEN-LAST:event_cmdLlenadoM2ActionPerformed

    private void cmdLlenadoA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenadoA2ActionPerformed

        double n;

        for (int i = 0; i < v2.length; i++) {
            n = (int) (Math.random() * 25 + 1);
            v1[i] = n;

         

        }

        JOptionPane.showMessageDialog(this, "Vector Llenado Con Exito");

        cmdCrear2.setEnabled(false);
        cmdLlenadoM2.setEnabled(false);
        cmdLlenadoA2.setEnabled(false);
        cmdMostrar2.setEnabled(true);
        cmdBorrar2.setEnabled(true);
        txtLD.setEditable(false);
    }//GEN-LAST:event_cmdLlenadoA2ActionPerformed

    private void cmdBorrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrar2ActionPerformed

        txtLD.setText("");
        txtR.setText("");
        txtED.setText("");
        txtLD.requestFocusInWindow();
        v2 = null;

        cmdCrear2.setEnabled(true);
        cmdLlenadoM2.setEnabled(false);
        cmdLlenadoA2.setEnabled(false);
        cmdMostrar2.setEnabled(false);
        cmdBorrar2.setEnabled(true);
        txtLD.setEditable(true);
    }//GEN-LAST:event_cmdBorrar2ActionPerformed

    private void cmdMostrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrar2ActionPerformed

        txtR.setText("");
        txtED.setText("");
        
        for (int i = 0; i < v2.length; i++) {
            
        txtED.append("" + v2[i]+ "\n");
               
        }

       
        cmdCrear2.setEnabled(false);
        cmdLlenadoM2.setEnabled(false);
        cmdLlenadoA2.setEnabled(false);
        cmdMostrar2.setEnabled(true);
        cmdBorrar2.setEnabled(true);
        txtLD.setEditable(false);
        
        
    }//GEN-LAST:event_cmdMostrar2ActionPerformed

    private void txtLUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLUKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLUKeyTyped

    private void cmdCrear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrear1ActionPerformed

        int L1;
        
        if (txtLU.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite La Longitud", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtLU.requestFocusInWindow();
        } else if (Integer.parseInt(txtLU.getText().trim()) == 0){
            JOptionPane.showMessageDialog(this, "Digite Una Longitud Superior A 0", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtLU.requestFocusInWindow();
            txtLU.selectAll();
        }
        else {
            
            
            
            L1 = Integer.parseInt(txtLU.getText());
            v1 = new double[L1];
            JOptionPane.showMessageDialog(this, "Vector Creado Satisfatoriamente");
            txtLU.setText("");
            
            
            cmdCrear1.setEnabled(false);
            cmdLlenadoM1.setEnabled(true);
            cmdLlenadoA1.setEnabled(true);
            cmdMostrar1.setEnabled(false);
            cmdBorrar1.setEnabled(true);
            txtLU.setEditable(false);
            
        }
    }//GEN-LAST:event_cmdCrear1ActionPerformed

    private void cmdLlenadoM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenadoM1ActionPerformed

        double n;
        

        for (int i = 0; i < v1.length; i++) {

            n = Double.parseDouble(JOptionPane.showInputDialog("Digite el elemento de la posicion " + i + " Del Vector Uno"));
            v1[i] = n;

                  }

        JOptionPane.showMessageDialog(this, "Vector Llenado Con Exito");

        cmdCrear1.setEnabled(false);
        cmdLlenadoM1.setEnabled(false);
        cmdLlenadoA1.setEnabled(false);
        cmdMostrar1.setEnabled(true);
        cmdBorrar1.setEnabled(true);
        txtLU.setEditable(false);
    }//GEN-LAST:event_cmdLlenadoM1ActionPerformed

    private void cmdLlenadoA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenadoA1ActionPerformed

        double n;

        for (int i = 0; i < v1.length; i++) {
            n = (int) (Math.random() * 25 + 1);
            v1[i] = n;

         

        }

        JOptionPane.showMessageDialog(this, "Vector Llenado Con Exito");

        cmdCrear2.setEnabled(false);
        cmdLlenadoM2.setEnabled(false);
        cmdLlenadoA2.setEnabled(false);
        cmdMostrar2.setEnabled(true);
        cmdBorrar2.setEnabled(true);
        txtLD.setEditable(false);
    }//GEN-LAST:event_cmdLlenadoA1ActionPerformed

    private void cmdBorrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrar1ActionPerformed

        txtLU.setText("");
        txtR.setText("");
        txtEU.setText("");
        txtLU.requestFocusInWindow();
        v1 = null;

        cmdCrear1.setEnabled(true);
        cmdLlenadoM1.setEnabled(false);
        cmdLlenadoA1.setEnabled(false);
        cmdMostrar1.setEnabled(false);
        cmdBorrar1.setEnabled(true);
        txtLU.setEditable(true);
        
    }//GEN-LAST:event_cmdBorrar1ActionPerformed

    private void cmdMostrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrar1ActionPerformed

        
        txtR.setText("");
        txtEU.setText("");
        for (int i = 0; i < v1.length; i++) {
            
        txtEU.append(""+v1[i]+ "\n");
               
        }
       
        cmdCrear1.setEnabled(false);
        cmdLlenadoM1.setEnabled(false);
        cmdLlenadoA1.setEnabled(false);
        cmdMostrar1.setEnabled(true);
        cmdBorrar1.setEnabled(true);
        txtLU.setEditable(false);
    }//GEN-LAST:event_cmdMostrar1ActionPerformed

    private void cmdBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarTodoActionPerformed

        txtLU.setText("");
        txtLD.setText("");
        txtEU.setText("");
        txtED.setText("");
        txtR.setText("");
        v1 = null;
        v2 = null;
        
        
        cmdCrear1.setEnabled(true);
        cmdLlenadoM1.setEnabled(false);
        cmdLlenadoA1.setEnabled(false);
        cmdMostrar1.setEnabled(false);
        cmdBorrar1.setEnabled(true);
        txtLU.setEditable(true);
        cmdCrear2.setEnabled(true);
        cmdLlenadoM2.setEnabled(false);
        cmdLlenadoA2.setEnabled(false);
        cmdMostrar2.setEnabled(false);
        cmdBorrar2.setEnabled(true);
        txtLD.setEditable(true);
        txtLU.requestFocusInWindow();
        cmdCalcular.setEnabled(true);
    }//GEN-LAST:event_cmdBorrarTodoActionPerformed

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed

        
        int l1;
        int L1;
        int L2;
        
        
        l1 = Integer.parseInt(JOptionPane.showInputDialog("Digite Los Numeros De Elementos a Calcular"));
        vS = new double [l1];
        vR = new double [l1];
        
       
        if (vS.length > v1.length) {
            JOptionPane.showMessageDialog(this, "El Numero De Elementos A Calcular No Puede Ser Mayor Que las Longitudes De Los Vectores","ERROR",JOptionPane.ERROR_MESSAGE);
        }
     
        else if (vS.length > v2.length) {
            JOptionPane.showMessageDialog(this, "El Numero De Elementos A Calcular No Puede Ser Mayor Que las Longitudes De Los Vectores","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else if (vR.length > v1.length) {
            JOptionPane.showMessageDialog(this, "El Numero De Elementos A Calcular No Puede Ser Mayor Que las Longitudes De Los Vectores","ERROR",JOptionPane.ERROR_MESSAGE);
        }
     
        else if (vR.length > v2.length) {
            JOptionPane.showMessageDialog(this, "El Numero De Elementos A Calcular No Puede Ser Mayor Que las Longitudes De Los Vectores","ERROR",JOptionPane.ERROR_MESSAGE);
        }
     
       
        else{
        txtR.append("La Suma De Los Vectores Es: \n");
         for (int i = 0; i < vS.length; i++) {
            vS[i] = v1[i] + v2[i];
            txtR.append("" + v1[i] + " + " + v2[i] + " = " + vS[i] +"\n");
        }
         
        txtR.append("La Resta De Los Vectores Es: \n"); 
        for (int i = 0; i < vR.length; i++) {
            vR[i] = v1[i] - v2[i];
            txtR.append("" + v1[i] + " - " + v2[i] + " = " + vR[i] +"\n");
        }
        
        cmdCrear1.setEnabled(true);
        cmdLlenadoM1.setEnabled(false);
        cmdLlenadoA1.setEnabled(false);
        cmdMostrar1.setEnabled(false);
        cmdBorrar1.setEnabled(true);
        txtLU.setEditable(false);
        cmdCrear2.setEnabled(true);
        cmdLlenadoM2.setEnabled(false);
        cmdLlenadoA2.setEnabled(false);
        cmdMostrar2.setEnabled(false);
        cmdBorrar2.setEnabled(true);
        cmdCalcular.setEnabled(false);
        txtLD.setEditable(false);
        
        }
    }//GEN-LAST:event_cmdCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VectorTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VectorTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VectorTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VectorTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VectorTres().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar1;
    private javax.swing.JButton cmdBorrar2;
    private javax.swing.JButton cmdBorrarTodo;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdCrear1;
    private javax.swing.JButton cmdCrear2;
    private javax.swing.JButton cmdLlenadoA1;
    private javax.swing.JButton cmdLlenadoA2;
    private javax.swing.JButton cmdLlenadoM1;
    private javax.swing.JButton cmdLlenadoM2;
    private javax.swing.JButton cmdMostrar1;
    private javax.swing.JButton cmdMostrar2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtED;
    private javax.swing.JTextArea txtEU;
    private javax.swing.JTextField txtLD;
    private javax.swing.JTextField txtLU;
    private javax.swing.JTextArea txtR;
    // End of variables declaration//GEN-END:variables
}
